In [1]:
 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv("Airline_delay_cause.csv")
df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,12,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",72.0,5.0,2.46,1.00,...,0.0,0.81,0.0,0.0,672.0,61.0,574.0,20.0,0.0,17.0
1,2023,12,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,7.0,4.25,0.00,...,0.0,1.75,0.0,0.0,348.0,252.0,0.0,33.0,0.0,63.0
2,2023,12,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",95.0,10.0,5.94,0.00,...,0.0,3.00,0.0,0.0,859.0,536.0,0.0,47.0,0.0,276.0
3,2023,12,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",23.0,2.0,0.56,0.00,...,0.0,1.44,1.0,0.0,75.0,9.0,0.0,0.0,0.0,66.0
4,2023,12,9E,Endeavor Air Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2111.0,256.0,76.88,8.75,...,0.0,117.94,1.0,0.0,21424.0,8906.0,732.0,1487.0,0.0,10299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77758,2020,1,YX,Republic Airline,TUS,"Tucson, AZ: Tucson International",7.0,0.0,0.00,0.00,...,0.0,0.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77759,2020,1,YX,Republic Airline,TVC,"Traverse City, MI: Cherry Capital",1.0,0.0,0.00,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77760,2020,1,YX,Republic Airline,TYS,"Knoxville, TN: McGhee Tyson",112.0,10.0,1.79,1.00,...,0.0,3.20,0.0,0.0,352.0,39.0,46.0,102.0,0.0,165.0
77761,2020,1,YX,Republic Airline,VPS,"Valparaiso, FL: Eglin AFB Destin Fort Walton B...",8.0,1.0,0.00,0.00,...,0.0,0.00,0.0,0.0,47.0,0.0,0.0,47.0,0.0,0.0
77762,2020,1,YX,Republic Airline,XNA,"Fayetteville, AR: Northwest Arkansas Regional",246.0,28.0,7.79,0.00,...,0.0,13.14,0.0,0.0,1446.0,347.0,0.0,277.0,0.0,822.0

In [3]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,12,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",72.0,5.0,2.46,1.00,...,0.0,0.81,0.0,0.0,672.0,61.0,574.0,20.0,0.0,17.0
1,2023,12,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,7.0,4.25,0.00,...,0.0,1.75,0.0,0.0,348.0,252.0,0.0,33.0,0.0,63.0
2,2023,12,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",95.0,10.0,5.94,0.00,...,0.0,3.00,0.0,0.0,859.0,536.0,0.0,47.0,0.0,276.0
3,2023,12,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",23.0,2.0,0.56,0.00,...,0.0,1.44,1.0,0.0,75.0,9.0,0.0,0.0,0.0,66.0
4,2023,12,9E,Endeavor Air Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2111.0,256.0,76.88,8.75,...,0.0,117.94,1.0,0.0,21424.0,8906.0,732.0,1487.0,0.0,10299.0

In [4]:
df.isnull()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77758,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
77759,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
77760,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
77761,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
77762,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
df.isnull().sum()

year                     0
month                    0
carrier                  0
carrier_name             0
airport                  0
airport_name             0
arr_flights            138
arr_del15              320
carrier_ct             138
weather_ct             138
nas_ct                 138
security_ct            138
late_aircraft_ct       138
arr_cancelled          138
arr_diverted           138
arr_delay              138
carrier_delay          138
weather_delay          138
nas_delay              138
security_delay         138
late_aircraft_delay    138
dtype: int64

In [6]:
#Remove null values from dataset
df_1=df.dropna(axis=0, how='any', inplace=False)

In [7]:
df_1.isnull().sum()

year                   0
month                  0
carrier                0
carrier_name           0
airport                0
airport_name           0
arr_flights            0
arr_del15              0
carrier_ct             0
weather_ct             0
nas_ct                 0
security_ct            0
late_aircraft_ct       0
arr_cancelled          0
arr_diverted           0
arr_delay              0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64

In [8]:

df_1.duplicated().sum()

0

In [9]:

df_1.dtypes

year                     int64
month                    int64
carrier                 object
carrier_name            object
airport                 object
airport_name            object
arr_flights            float64
arr_del15              float64
carrier_ct             float64
weather_ct             float64
nas_ct                 float64
security_ct            float64
late_aircraft_ct       float64
arr_cancelled          float64
arr_diverted           float64
arr_delay              float64
carrier_delay          float64
weather_delay          float64
nas_delay              float64
security_delay         float64
late_aircraft_delay    float64
dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
encoder = LabelEncoder()
df_1['carrier_name'] = encoder.fit_transform(df_1['carrier_name'])
carrier_name = {index : label for index, label in enumerate(encoder.classes_)}
carrier_name

C:\Users\sasan\AppData\Local\Temp\ipykernel_13044\2594446184.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['carrier_name'] = encoder.fit_transform(df_1['carrier_name'])

{0: 'Alaska Airlines Inc.',
 1: 'Allegiant Air',
 2: 'American Airlines Inc.',
 3: 'Delta Air Lines Inc.',
 4: 'Endeavor Air Inc.',
 5: 'Envoy Air',
 6: 'ExpressJet Airlines LLC',
 7: 'Frontier Airlines Inc.',
 8: 'Hawaiian Airlines Inc.',
 9: 'Horizon Air',
 10: 'JetBlue Airways',
 11: 'Mesa Airlines Inc.',
 12: 'PSA Airlines Inc.',
 13: 'Republic Airline',
 14: 'SkyWest Airlines Inc.',
 15: 'Southwest Airlines Co.',
 16: 'Spirit Air Lines',
 17: 'United Air Lines Inc.'}

In [12]:
df_1['airport'] = encoder.fit_transform(df_1['airport'])
airport = {index : label for index, label in enumerate(encoder.classes_)}
airport

C:\Users\sasan\AppData\Local\Temp\ipykernel_13044\4136530110.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['airport'] = encoder.fit_transform(df_1['airport'])

{0: 'ABE',
 1: 'ABI',
 2: 'ABQ',
 3: 'ABR',
 4: 'ABY',
 5: 'ACK',
 6: 'ACT',
 7: 'ACV',
 8: 'ACY',
 9: 'ADK',
 10: 'ADQ',
 11: 'AEX',
 12: 'AGS',
 13: 'AKN',
 14: 'ALB',
 15: 'ALO',
 16: 'ALS',
 17: 'ALW',
 18: 'AMA',
 19: 'ANC',
 20: 'APN',
 21: 'ASE',
 22: 'ATL',
 23: 'ATW',
 24: 'ATY',
 25: 'AUS',
 26: 'AVL',
 27: 'AVP',
 28: 'AZA',
 29: 'AZO',
 30: 'BDL',
 31: 'BET',
 32: 'BFF',
 33: 'BFL',
 34: 'BFM',
 35: 'BGM',
 36: 'BGR',
 37: 'BHM',
 38: 'BIH',
 39: 'BIL',
 40: 'BIS',
 41: 'BJI',
 42: 'BKG',
 43: 'BLI',
 44: 'BLV',
 45: 'BMI',
 46: 'BNA',
 47: 'BOI',
 48: 'BOS',
 49: 'BPT',
 50: 'BQK',
 51: 'BQN',
 52: 'BRD',
 53: 'BRO',
 54: 'BRW',
 55: 'BTM',
 56: 'BTR',
 57: 'BTV',
 58: 'BUF',
 59: 'BUR',
 60: 'BWI',
 61: 'BZN',
 62: 'CAE',
 63: 'CAK',
 64: 'CDB',
 65: 'CDC',
 66: 'CDV',
 67: 'CGI',
 68: 'CHA',
 69: 'CHO',
 70: 'CHS',
 71: 'CID',
 72: 'CIU',
 73: 'CKB',
 74: 'CLE',
 75: 'CLL',
 76: 'CLT',
 77: 'CMH',
 78: 'CMI',
 79: 'CMX',
 80: 'CNY',
 81: 'COD',
 82: 'COS',
 83: 'COU',
 84: 'CPR',
 85: 'CRP',
 86: 'CRW',
 87: 'CSG',
 88: 'CVG',
 89: 'CWA',
 90: 'CYS',
 91: 'DAB',
 92: 'DAL',
 93: 'DAY',
 94: 'DBQ',
 95: 'DCA',
 96: 'DDC',
 97: 'DEC',
 98: 'DEN',
 99: 'DFW',
 100: 'DHN',
 101: 'DIK',
 102: 'DLG',
 103: 'DLH',
 104: 'DRO',
 105: 'DRT',
 106: 'DSM',
 107: 'DTW',
 108: 'DVL',
 109: 'EAR',
 110: 'EAT',
 111: 'EAU',
 112: 'ECP',
 113: 'EGE',
 114: 'EKO',
 115: 'ELM',
 116: 'ELP',
 117: 'ERI',
 118: 'ESC',
 119: 'EUG',
 120: 'EVV',
 121: 'EWN',
 122: 'EWR',
 123: 'EYW',
 124: 'FAI',
 125: 'FAR',
 126: 'FAT',
 127: 'FAY',
 128: 'FCA',
 129: 'FLG',
 130: 'FLL',
 131: 'FLO',
 132: 'FNT',
 133: 'FOD',
 134: 'FSD',
 135: 'FSM',
 136: 'FWA',
 137: 'GCC',
 138: 'GCK',
 139: 'GEG',
 140: 'GFK',
 141: 'GGG',
 142: 'GJT',
 143: 'GNV',
 144: 'GPT',
 145: 'GRB',
 146: 'GRI',
 147: 'GRK',
 148: 'GRR',
 149: 'GSO',
 150: 'GSP',
 151: 'GST',
 152: 'GTF',
 153: 'GTR',
 154: 'GUC',
 155: 'GUM',
 156: 'HDN',
 157: 'HGR',
 158: 'HHH',
 159: 'HIB',
 160: 'HLN',
 161: 'HNL',
 162: 'HOB',
 163: 'HOU',
 164: 'HPN',
 165: 'HRL',
 166: 'HSV',
 167: 'HTS',
 168: 'HVN',
 169: 'HYA',
 170: 'HYS',
 171: 'IAD',
 172: 'IAG',
 173: 'IAH',
 174: 'ICT',
 175: 'IDA',
 176: 'IFP',
 177: 'ILG',
 178: 'ILM',
 179: 'IMT',
 180: 'IND',
 181: 'INL',
 182: 'IPT',
 183: 'ISP',
 184: 'ITH',
 185: 'ITO',
 186: 'JAC',
 187: 'JAN',
 188: 'JAX',
 189: 'JFK',
 190: 'JLN',
 191: 'JMS',
 192: 'JNU',
 193: 'JST',
 194: 'KOA',
 195: 'KTN',
 196: 'LAN',
 197: 'LAR',
 198: 'LAS',
 199: 'LAW',
 200: 'LAX',
 201: 'LBB',
 202: 'LBE',
 203: 'LBF',
 204: 'LBL',
 205: 'LCH',
 206: 'LCK',
 207: 'LEX',
 208: 'LFT',
 209: 'LGA',
 210: 'LGB',
 211: 'LIH',
 212: 'LIT',
 213: 'LNK',
 214: 'LRD',
 215: 'LSE',
 216: 'LWB',
 217: 'LWS',
 218: 'LYH',
 219: 'MAF',
 220: 'MBS',
 221: 'MCI',
 222: 'MCO',
 223: 'MCW',
 224: 'MDT',
 225: 'MDW',
 226: 'MEI',
 227: 'MEM',
 228: 'MFE',
 229: 'MFR',
 230: 'MGM',
 231: 'MHK',
 232: 'MHT',
 233: 'MIA',
 234: 'MKE',
 235: 'MKG',
 236: 'MLB',
 237: 'MLI',
 238: 'MLU',
 239: 'MMH',
 240: 'MOB',
 241: 'MOT',
 242: 'MQT',
 243: 'MRY',
 244: 'MSN',
 245: 'MSO',
 246: 'MSP',
 247: 'MSY',
 248: 'MTJ',
 249: 'MVY',
 250: 'MYR',
 251: 'OAJ',
 252: 'OAK',
 253: 'OGD',
 254: 'OGG',
 255: 'OGS',
 256: 'OKC',
 257: 'OMA',
 258: 'OME',
 259: 'ONT',
 260: 'ORD',
 261: 'ORF',
 262: 'ORH',
 263: 'OTH',
 264: 'OTZ',
 265: 'OWB',
 266: 'PAE',
 267: 'PAH',
 268: 'PBG',
 269: 'PBI',
 270: 'PDX',
 271: 'PGD',
 272: 'PGV',
 273: 'PHF',
 274: 'PHL',
 275: 'PHX',
 276: 'PIA',
 277: 'PIB',
 278: 'PIE',
 279: 'PIH',
 280: 'PIR',
 281: 'PIT',
 282: 'PLN',
 283: 'PNS',
 284: 'PPG',
 285: 'PRC',
 286: 'PSC',
 287: 'PSE',
 288: 'PSG',
 289: 'PSM',
 290: 'PSP',
 291: 'PUB',
 292: 'PUW',
 293: 'PVD',
 294: 'PVU',
 295: 'PWM',
 296: 'RAP',
 297: 'RDD',
 298: 'RDM',
 299: 'RDU',
 300: 'RFD',
 301: 'RHI',
 302: 'RIC',
 303: 'RIW',
 304: 'RKS',
 305: 'RNO',
 306: 'ROA',
 307: 'ROC',
 308: 'ROW',
 309: 'RST',
 310: 'RSW',
 311: 'SAF',
 312: 'SAN',
 313: 'SAT',
 314: 'SAV',
 315: 'SBA',
 316: 'SBN',
 317: 'SBP',
 318: 'SCC',
 319: 'SCE',
 320: 'SCK',
 321: 'SDF',
 322: 'SEA',
 323: 'SFB',
 324: 'SFO',
 325: 'SGF',
 326: 'SGU',
 327: 'SHD',
 328: 'SHR',
 329: 'SHV',
 330: 'SIT',
 331: 'SJC',
 332: 'SJT',
 333: 'SJU',
 334: 'SLC',
 335: 'SLN',
 336: 'SMF',
 337: 'SMX',
 338: 'SNA',
 339: 'SPI',
 340: 'SPN',
 341: 'SPS',
 342: 'SRQ',
 343: 'STC',
 344: 'STL',
 345: 'STS',
 346: 'STT',
 347: 'STX',
 348: 'SUN',
 349: 'SUX',
 350: 'SWF',
 351: 'SWO',
 352: 'SYR',
 353: 'TBN',
 354: 'TLH',
 355: 'TOL',
 356: 'TPA',
 357: 'TRI',
 358: 'TTN',
 359: 'TUL',
 360: 'TUS',
 361: 'TVC',
 362: 'TWF',
 363: 'TXK',
 364: 'TYR',
 365: 'TYS',
 366: 'UIN',
 367: 'USA',
 368: 'VCT',
 369: 'VEL',
 370: 'VLD',
 371: 'VPS',
 372: 'WRG',
 373: 'WYS',
 374: 'XNA',
 375: 'XWA',
 376: 'YAK',
 377: 'YKM',
 378: 'YUM'}

In [13]:
df_1['airport_name'] = encoder.fit_transform(df_1['airport_name'])
airport_name = {index : label for index, label in enumerate(encoder.classes_)}
airport_name

C:\Users\sasan\AppData\Local\Temp\ipykernel_13044\110047566.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['airport_name'] = encoder.fit_transform(df_1['airport_name'])

{0: 'Aberdeen, SD: Aberdeen Regional',
 1: 'Abilene, TX: Abilene Regional',
 2: 'Adak Island, AK: Adak',
 3: 'Aguadilla, PR: Rafael Hernandez',
 4: 'Akron, OH: Akron-Canton Regional',
 5: 'Alamosa, CO: San Luis Valley Regional/Bergman Field',
 6: 'Albany, GA: Southwest Georgia Regional',
 7: 'Albany, NY: Albany International',
 8: 'Albuquerque, NM: Albuquerque International Sunport',
 9: 'Alexandria, LA: Alexandria International',
 10: 'Allentown/Bethlehem/Easton, PA: Lehigh Valley International',
 11: 'Alpena, MI: Alpena County Regional',
 12: 'Amarillo, TX: Rick Husband Amarillo International',
 13: 'Anchorage, AK: Ted Stevens Anchorage International',
 14: 'Appleton, WI: Appleton International',
 15: 'Arcata/Eureka, CA: California Redwood Coast Humboldt County',
 16: 'Asheville, NC: Asheville Regional',
 17: 'Ashland, WV: Tri-State/Milton J. Ferguson Field',
 18: 'Aspen, CO: Aspen Pitkin County Sardy Field',
 19: 'Atlanta, GA: Hartsfield-Jackson Atlanta International',
 20: 'Atlantic City, NJ: Atlantic City International',
 21: 'Augusta, GA: Augusta Regional at Bush Field',
 22: 'Austin, TX: Austin - Bergstrom International',
 23: 'Bakersfield, CA: Meadows Field',
 24: 'Baltimore, MD: Baltimore/Washington International Thurgood Marshall',
 25: 'Bangor, ME: Bangor International',
 26: 'Barrow, AK: Wiley Post/Will Rogers Memorial',
 27: 'Baton Rouge, LA: Baton Rouge Metropolitan/Ryan Field',
 28: 'Beaumont/Port Arthur, TX: Jack Brooks Regional',
 29: 'Belleville, IL: Scott AFB MidAmerica St Louis',
 30: 'Belleville, IL: Scott AFB/MidAmerica',
 31: 'Bellingham, WA: Bellingham International',
 32: 'Bemidji, MN: Bemidji Regional',
 33: 'Bend/Redmond, OR: Roberts Field',
 34: 'Bethel, AK: Bethel Airport',
 35: 'Billings, MT: Billings Logan International',
 36: 'Binghamton, NY: Greater Binghamton/Edwin A. Link Field',
 37: 'Birmingham, AL: Birmingham-Shuttlesworth International',
 38: 'Bishop, CA: Bishop Airport',
 39: 'Bismarck/Mandan, ND: Bismarck Municipal',
 40: 'Bloomington/Normal, IL: Central Il Regional Airport at Bloomington',
 41: 'Boise, ID: Boise Air Terminal',
 42: 'Boston, MA: Logan International',
 43: 'Bozeman, MT: Bozeman Yellowstone International',
 44: 'Brainerd, MN: Brainerd Lakes Regional',
 45: 'Branson, MO: Branson Airport',
 46: 'Bristol/Johnson City/Kingsport, TN: Tri Cities',
 47: 'Brownsville, TX: Brownsville South Padre Island International',
 48: 'Brunswick, GA: Brunswick Golden Isles',
 49: 'Buffalo, NY: Buffalo Niagara International',
 50: 'Bullhead City, AZ: Laughlin/Bullhead International',
 51: 'Burbank, CA: Bob Hope',
 52: 'Burlington, VT: Burlington International',
 53: 'Butte, MT: Bert Mooney',
 54: 'Cape Girardeau, MO: Cape Girardeau Regional',
 55: 'Casper, WY: Casper/Natrona County International',
 56: 'Cedar City, UT: Cedar City Regional',
 57: 'Cedar Rapids/Iowa City, IA: The Eastern Iowa',
 58: 'Champaign/Urbana, IL: University of Illinois/Willard',
 59: 'Charleston, SC: Charleston AFB/International',
 60: 'Charleston/Dunbar, WV: West Virginia International Yeager',
 61: 'Charleston/Dunbar, WV: Yeager',
 62: 'Charlotte Amalie, VI: Cyril E King',
 63: 'Charlotte, NC: Charlotte Douglas International',
 64: 'Charlottesville, VA: Charlottesville Albemarle',
 65: 'Chattanooga, TN: Lovell Field',
 66: 'Cheyenne, WY: Cheyenne Regional/Jerry Olson Field',
 67: 'Chicago, IL: Chicago Midway International',
 68: "Chicago, IL: Chicago O'Hare International",
 69: 'Christiansted, VI: Henry E. Rohlsen',
 70: 'Cincinnati, OH: Cincinnati/Northern Kentucky International',
 71: 'Clarksburg/Fairmont, WV: North Central West Virginia',
 72: 'Cleveland, OH: Cleveland-Hopkins International',
 73: 'Cody, WY: Yellowstone Regional',
 74: 'Cold Bay, AK: Cold Bay Airport',
 75: 'College Station/Bryan, TX: Easterwood Field',
 76: 'Colorado Springs, CO: City of Colorado Springs Municipal',
 77: 'Columbia, MO: Columbia Regional',
 78: 'Columbia, SC: Columbia Metropolitan',
 79: 'Columbus, GA: Columbus Airport',
 80: 'Columbus, MS: Golden Triangle Regional',
 81: 'Columbus, OH: John Glenn Columbus International',
 82: 'Columbus, OH: Rickenbacker International',
 83: 'Concord, NC: Concord Padgett Regional',
 84: 'Cordova, AK: Merle K Mudhole Smith',
 85: 'Corpus Christi, TX: Corpus Christi International',
 86: 'Dallas, TX: Dallas Love Field',
 87: 'Dallas/Fort Worth, TX: Dallas/Fort Worth International',
 88: 'Dayton, OH: James M Cox/Dayton International',
 89: 'Daytona Beach, FL: Daytona Beach International',
 90: 'Deadhorse, AK: Deadhorse Airport',
 91: 'Decatur, IL: Decatur Airport',
 92: 'Del Rio, TX: Del Rio International',
 93: 'Denver, CO: Denver International',
 94: 'Des Moines, IA: Des Moines International',
 95: 'Detroit, MI: Detroit Metro Wayne County',
 96: 'Devils Lake, ND: Devils Lake Regional',
 97: 'Dickinson, ND: Dickinson - Theodore Roosevelt Regional',
 98: 'Dillingham, AK: Dillingham Airport',
 99: 'Dodge City, KS: Dodge City Regional',
 100: 'Dothan, AL: Dothan Regional',
 101: 'Dubuque, IA: Dubuque Regional',
 102: 'Duluth, MN: Duluth International',
 103: 'Durango, CO: Durango La Plata County',
 104: 'Eagle, CO: Eagle County Regional',
 105: 'Eau Claire, WI: Chippewa Valley Regional',
 106: 'El Paso, TX: El Paso International',
 107: 'Elko, NV: Elko Regional',
 108: 'Elmira/Corning, NY: Elmira/Corning Regional',
 109: 'Erie, PA: Erie International/Tom Ridge Field',
 110: 'Escanaba, MI: Delta County',
 111: 'Eugene, OR: Mahlon Sweet Field',
 112: 'Evansville, IN: Evansville Regional',
 113: 'Everett, WA: Snohomish County',
 114: 'Fairbanks, AK: Fairbanks International',
 115: 'Fargo, ND: Hector International',
 116: 'Fayetteville, AR: Northwest Arkansas National',
 117: 'Fayetteville, AR: Northwest Arkansas Regional',
 118: 'Fayetteville, NC: Fayetteville Regional/Grannis Field',
 119: 'Flagstaff, AZ: Flagstaff Pulliam',
 120: 'Flint, MI: Bishop International',
 121: 'Florence, SC: Florence Regional',
 122: 'Fort Dodge, IA: Fort Dodge Regional',
 123: 'Fort Lauderdale, FL: Fort Lauderdale-Hollywood International',
 124: 'Fort Leonard Wood, MO: Waynesville-St. Robert Regional Forney Field',
 125: 'Fort Myers, FL: Southwest Florida International',
 126: 'Fort Smith, AR: Fort Smith Regional',
 127: 'Fort Wayne, IN: Fort Wayne International',
 128: 'Fresno, CA: Fresno Yosemite International',
 129: 'Gainesville, FL: Gainesville Regional',
 130: 'Garden City, KS: Garden City Regional',
 131: 'Gillette, WY: Gillette Campbell County',
 132: 'Gillette, WY: Northeast Wyoming Regional',
 133: 'Grand Forks, ND: Grand Forks International',
 134: 'Grand Island, NE: Central Nebraska Regional',
 135: 'Grand Junction, CO: Grand Junction Regional',
 136: 'Grand Rapids, MI: Gerald R. Ford International',
 137: 'Great Falls, MT: Great Falls International',
 138: 'Green Bay, WI: Green Bay Austin Straubel International',
 139: 'Greensboro/High Point, NC: Piedmont Triad International',
 140: 'Greenville, NC: Pitt Greenville',
 141: 'Greer, SC: Greenville-Spartanburg International',
 142: 'Guam, TT: Guam International',
 143: 'Gulfport/Biloxi, MS: Gulfport-Biloxi International',
 144: 'Gunnison, CO: Gunnison-Crested Butte Regional',
 145: 'Gustavus, AK: Gustavus Airport',
 146: 'Hagerstown, MD: Hagerstown Regional-Richard A. Henson Field',
 147: 'Hancock/Houghton, MI: Houghton County Memorial',
 148: 'Harlingen/San Benito, TX: Valley International',
 149: 'Harrisburg, PA: Harrisburg International',
 150: 'Hartford, CT: Bradley International',
 151: 'Hattiesburg/Laurel, MS: Hattiesburg-Laurel Regional',
 152: 'Hayden, CO: Yampa Valley',
 153: 'Hays, KS: Hays Regional',
 154: 'Helena, MT: Helena Regional',
 155: 'Hibbing, MN: Range Regional',
 156: 'Hilo, HI: Hilo International',
 157: 'Hilton Head, SC: Hilton Head Airport',
 158: 'Hobbs, NM: Lea County Regional',
 159: 'Honolulu, HI: Daniel K Inouye International',
 160: 'Houston, TX: George Bush Intercontinental/Houston',
 161: 'Houston, TX: William P Hobby',
 162: 'Huntsville, AL: Huntsville International-Carl T Jones Field',
 163: 'Hyannis, MA: Barnstable Municipal-Boardman/Polando Field',
 164: 'Hyannis, MA: Cape Cod Gateway',
 165: 'Idaho Falls, ID: Idaho Falls Regional',
 166: 'Indianapolis, IN: Indianapolis International',
 167: 'International Falls, MN: Falls International Einarson Field',
 168: 'Iron Mountain/Kingsfd, MI: Ford',
 169: 'Islip, NY: Long Island MacArthur',
 170: 'Ithaca/Cortland, NY: Ithaca Tompkins International',
 171: 'Ithaca/Cortland, NY: Ithaca Tompkins Regional',
 172: 'Jackson, WY: Jackson Hole',
 173: 'Jackson/Vicksburg, MS: Jackson Medgar Wiley Evers International',
 174: 'Jacksonville, FL: Jacksonville International',
 175: 'Jacksonville/Camp Lejeune, NC: Albert J Ellis',
 176: 'Jamestown, ND: Jamestown Regional',
 177: 'Johnstown, PA: John Murtha Johnstown-Cambria County',
 178: 'Joplin, MO: Joplin Regional',
 179: 'Juneau, AK: Juneau International',
 180: 'Kahului, HI: Kahului Airport',
 181: 'Kalamazoo, MI: Kalamazoo/Battle Creek International',
 182: 'Kalispell, MT: Glacier Park International',
 183: 'Kansas City, MO: Kansas City International',
 184: 'Kearney, NE: Kearney Regional',
 185: 'Ketchikan, AK: Ketchikan International',
 186: 'Key West, FL: Key West International',
 187: 'Killeen, TX: Robert Gray AAF',
 188: 'King Salmon, AK: King Salmon Airport',
 189: 'Knoxville, TN: McGhee Tyson',
 190: 'Kodiak, AK: Kodiak Airport',
 191: 'Kona, HI: Ellison Onizuka Kona International at Keahole',
 192: 'Kotzebue, AK: Ralph Wien Memorial',
 193: 'La Crosse, WI: La Crosse Regional',
 194: 'Lafayette, LA: Lafayette Regional Paul Fournet Field',
 195: 'Lake Charles, LA: Lake Charles Regional',
 196: 'Lansing, MI: Capital Region International',
 197: 'Laramie, WY: Laramie Regional',
 198: 'Laredo, TX: Laredo International',
 199: 'Las Vegas, NV: Harry Reid International',
 200: 'Las Vegas, NV: McCarran International',
 201: 'Latrobe, PA: Arnold Palmer Regional',
 202: 'Lawton/Fort Sill, OK: Lawton-Fort Sill Regional',
 203: 'Lewisburg, WV: Greenbrier Valley',
 204: 'Lewiston, ID: Lewiston Nez Perce County',
 205: 'Lexington, KY: Blue Grass',
 206: 'Liberal, KS: Liberal Mid-America Regional',
 207: 'Lihue, HI: Lihue Airport',
 208: 'Lincoln, NE: Lincoln Airport',
 209: 'Little Rock, AR: Bill and Hillary Clinton Nat Adams Field',
 210: 'Long Beach, CA: Long Beach Airport',
 211: 'Longview, TX: East Texas Regional',
 212: 'Los Angeles, CA: Los Angeles International',
 213: 'Louisville, KY: Louisville Muhammad Ali International',
 214: 'Lubbock, TX: Lubbock Preston Smith International',
 215: 'Lynchburg, VA: Lynchburg Regional/Preston Glenn Field',
 216: 'Madison, WI: Dane County Regional-Truax Field',
 217: 'Mammoth Lakes, CA: Mammoth Lakes Airport',
 218: 'Manchester, NH: Manchester Boston Regional',
 219: 'Manchester, NH: Manchester-Boston Regional',
 220: 'Manhattan/Ft. Riley, KS: Manhattan Regional',
 221: 'Marquette, MI: Marquette Sawyer Regional',
 222: 'Marquette, MI: Sawyer International',
 223: "Martha's Vineyard, MA: Martha's Vineyard Airport",
 224: 'Mason City, IA: Mason City Municipal',
 225: 'Medford, OR: Rogue Valley International - Medford',
 226: 'Melbourne, FL: Melbourne International',
 227: 'Melbourne, FL: Melbourne Orlando International',
 228: 'Memphis, TN: Memphis International',
 229: 'Meridian, MS: Key Field',
 230: 'Miami, FL: Miami International',
 231: 'Midland/Odessa, TX: Midland International Air and Space Port',
 232: 'Milwaukee, WI: General Mitchell International',
 233: 'Minneapolis, MN: Minneapolis-St Paul International',
 234: 'Minot, ND: Minot International',
 235: 'Mission/McAllen/Edinburg, TX: McAllen International',
 236: 'Mission/McAllen/Edinburg, TX: McAllen Miller International',
 237: 'Missoula, MT: Missoula International',
 238: 'Missoula, MT: Missoula Montana',
 239: 'Moab, UT: Canyonlands Field',
 240: 'Moab, UT: Canyonlands Regional',
 241: 'Mobile, AL: Mobile Downtown',
 242: 'Mobile, AL: Mobile Regional',
 243: 'Moline, IL: Quad Cities International',
 244: 'Moline, IL: Quad City International',
 245: 'Monroe, LA: Monroe Regional',
 246: 'Monterey, CA: Monterey Regional',
 247: 'Montgomery, AL: Montgomery Regional',
 248: 'Montrose/Delta, CO: Montrose Regional',
 249: 'Mosinee, WI: Central Wisconsin',
 250: 'Muskegon, MI: Muskegon County',
 251: 'Myrtle Beach, SC: Myrtle Beach International',
 252: 'Nantucket, MA: Nantucket Memorial',
 253: 'Nashville, TN: Nashville International',
 254: 'New Bern/Morehead/Beaufort, NC: Coastal Carolina Regional',
 255: 'New Haven, CT: Tweed New Haven',
 256: 'New Orleans, LA: Louis Armstrong New Orleans International',
 257: 'New York, NY: John F. Kennedy International',
 258: 'New York, NY: LaGuardia',
 259: 'Newark, NJ: Newark Liberty International',
 260: 'Newburgh/Poughkeepsie, NY: New York Stewart International',
 261: 'Newport News/Williamsburg, VA: Newport News/Williamsburg International',
 262: 'Niagara Falls, NY: Niagara Falls International',
 263: 'Nome, AK: Nome Airport',
 264: 'Norfolk, VA: Norfolk International',
 265: 'North Bend/Coos Bay, OR: Southwest Oregon Regional',
 266: 'North Platte, NE: North Platte Regional Airport Lee Bird Field',
 267: 'Oakland, CA: Metro Oakland International',
 268: 'Oakland, CA: Metropolitan Oakland International',
 269: 'Ogden, UT: Ogden-Hinckley',
 270: 'Ogdensburg, NY: Ogdensburg International',
 271: 'Oklahoma City, OK: Will Rogers World',
 272: 'Omaha, NE: Eppley Airfield',
 273: 'Ontario, CA: Ontario International',
 274: 'Orlando, FL: Orlando International',
 275: 'Owensboro, KY: Owensboro Daviess County Regional',
 276: 'Paducah, KY: Barkley Regional',
 277: 'Pago Pago, TT: Pago Pago International',
 278: 'Palm Springs, CA: Palm Springs International',
 279: 'Panama City, FL: Northwest Florida Beaches International',
 280: 'Pasco/Kennewick/Richland, WA: Tri Cities',
 281: 'Pellston, MI: Pellston Regional Airport of Emmet County',
 282: 'Pensacola, FL: Pensacola International',
 283: 'Peoria, IL: General Downing - Peoria International',
 284: 'Petersburg, AK: Petersburg James A Johnson',
 285: 'Philadelphia, PA: Philadelphia International',
 286: 'Phoenix, AZ: Phoenix - Mesa Gateway',
 287: 'Phoenix, AZ: Phoenix Sky Harbor International',
 288: 'Pierre, SD: Pierre Regional',
 289: 'Pittsburgh, PA: Pittsburgh International',
 290: 'Plattsburgh, NY: Plattsburgh International',
 291: 'Pocatello, ID: Pocatello Regional',
 292: 'Ponce, PR: Mercedita',
 293: 'Portland, ME: Portland International Jetport',
 294: 'Portland, OR: Portland International',
 295: 'Portsmouth, NH: Portsmouth International at Pease',
 296: 'Prescott, AZ: Prescott Regional Ernest A Love Field',
 297: 'Providence, RI: Rhode Island Tf Green International',
 298: 'Providence, RI: Theodore Francis Green State',
 299: 'Provo, UT: Provo Municipal',
 300: 'Pueblo, CO: Pueblo Memorial',
 301: 'Pullman, WA: Pullman Moscow Regional',
 302: 'Punta Gorda, FL: Punta Gorda Airport',
 303: 'Quincy, IL: Quincy Regional-Baldwin Field',
 304: 'Raleigh/Durham, NC: Raleigh-Durham International',
 305: 'Rapid City, SD: Rapid City Regional',
 306: 'Redding, CA: Redding Municipal',
 307: 'Redding, CA: Redding Regional',
 308: 'Reno, NV: Reno/Tahoe International',
 309: 'Rhinelander, WI: Rhinelander/Oneida County',
 310: 'Richmond, VA: Richmond International',
 311: 'Riverton/Lander, WY: Central Wyoming Regional',
 312: 'Riverton/Lander, WY: Riverton Regional',
 313: 'Roanoke, VA: Roanoke Blacksburg Regional',
 314: 'Roanoke, VA: Roanoke Blacksburg Regional Woodrum Field',
 315: 'Rochester, MN: Rochester International',
 316: 'Rochester, NY: Frederick Douglass Grtr Rochester International',
 317: 'Rochester, NY: Greater Rochester International',
 318: 'Rock Springs, WY: Southwest Wyoming Regional',
 319: 'Rockford, IL: Chicago/Rockford International',
 320: 'Roswell, NM: Roswell Air Center',
 321: 'Roswell, NM: Roswell International Air Center',
 322: 'Sacramento, CA: Sacramento International',
 323: 'Saginaw/Bay City/Midland, MI: MBS International',
 324: 'Saipan, TT: Francisco C. Ada Saipan International',
 325: 'Salina, KS: Salina Regional',
 326: 'Salt Lake City, UT: Salt Lake City International',
 327: 'San Angelo, TX: San Angelo Regional/Mathis Field',
 328: 'San Antonio, TX: San Antonio International',
 329: 'San Diego, CA: San Diego International',
 330: 'San Francisco, CA: San Francisco International',
 331: 'San Jose, CA: Norman Y. Mineta San Jose International',
 332: 'San Juan, PR: Luis Munoz Marin International',
 333: 'San Luis Obispo, CA: San Luis County Regional',
 334: 'Sanford, FL: Orlando Sanford International',
 335: 'Santa Ana, CA: John Wayne Airport-Orange County',
 336: 'Santa Barbara, CA: Santa Barbara Municipal',
 337: 'Santa Fe, NM: Santa Fe Municipal',
 338: 'Santa Maria, CA: Santa Maria Public/Capt. G. Allan Hancock Field',
 339: 'Santa Rosa, CA: Charles M. Schulz - Sonoma County',
 340: 'Sarasota/Bradenton, FL: Sarasota/Bradenton International',
 341: 'Sault Ste. Marie, MI: Chippewa County International',
 342: 'Savannah, GA: Savannah/Hilton Head International',
 343: 'Scottsbluff, NE: Western Neb. Regional/William B. Heilig Field',
 344: 'Scranton/Wilkes-Barre, PA: Wilkes Barre Scranton International',
 345: 'Seattle, WA: Seattle/Tacoma International',
 346: 'Sheridan, WY: Sheridan County',
 347: 'Shreveport, LA: Shreveport Regional',
 348: 'Sioux City, IA: Sioux Gateway Brig Gen Bud Day Field',
 349: 'Sioux Falls, SD: Joe Foss Field',
 350: 'Sitka, AK: Sitka Rocky Gutierrez',
 351: 'South Bend, IN: South Bend International',
 352: 'Spokane, WA: Spokane International',
 353: 'Springfield, IL: Abraham Lincoln Capital',
 354: 'Springfield, MO: Springfield-Branson National',
 355: 'St. Cloud, MN: St. Cloud Regional',
 356: 'St. George, UT: St George Regional',
 357: 'St. Louis, MO: St Louis Lambert International',
 358: 'St. Petersburg, FL: St Pete Clearwater International',
 359: 'State College, PA: University Park',
 360: 'Staunton, VA: Shenandoah Valley Regional',
 361: 'Stillwater, OK: Stillwater Regional',
 362: 'Stockton, CA: Stockton Metro',
 363: 'Stockton, CA: Stockton Metropolitan',
 364: 'Sun Valley/Hailey/Ketchum, ID: Friedman Memorial',
 365: 'Syracuse, NY: Syracuse Hancock International',
 366: 'Tallahassee, FL: Tallahassee International',
 367: 'Tampa, FL: Tampa International',
 368: 'Texarkana, AR: Texarkana Regional-Webb Field',
 369: 'Toledo, OH: Eugene F Kranz Toledo Express',
 370: 'Toledo, OH: Toledo Express',
 371: 'Traverse City, MI: Cherry Capital',
 372: 'Trenton, NJ: Trenton Mercer',
 373: 'Tucson, AZ: Tucson International',
 374: 'Tulsa, OK: Tulsa International',
 375: 'Twin Falls, ID: Joslin Field - Magic Valley Regional',
 376: 'Tyler, TX: Tyler Pounds Regional',
 377: 'Valdosta, GA: Valdosta Regional',
 378: 'Valparaiso, FL: Eglin AFB Destin Fort Walton Beach',
 379: 'Vernal, UT: Vernal Regional',
 380: 'Victoria, TX: Victoria Regional',
 381: 'Waco, TX: Waco Regional',
 382: 'Walla Walla, WA: Walla Walla Regional',
 383: 'Washington, DC: Ronald Reagan Washington National',
 384: 'Washington, DC: Washington Dulles International',
 385: 'Waterloo, IA: Waterloo Regional',
 386: 'Watertown, SD: Watertown Regional',
 387: 'Wenatchee, WA: Pangborn Memorial',
 388: 'West Palm Beach/Palm Beach, FL: Palm Beach International',
 389: 'West Yellowstone, MT: Yellowstone',
 390: 'White Plains, NY: Westchester County',
 391: 'Wichita Falls, TX: Sheppard AFB/Wichita Falls Municipal',
 392: 'Wichita, KS: Wichita Dwight D Eisenhower National',
 393: 'Williamsport, PA: Williamsport Regional',
 394: 'Williston, ND: Williston Basin International',
 395: 'Wilmington, DE: New Castle',
 396: 'Wilmington, NC: Wilmington International',
 397: 'Worcester, MA: Worcester Regional',
 398: 'Wrangell, AK: Wrangell Airport',
 399: 'Yakima, WA: Yakima Air Terminal/McAllister Field',
 400: 'Yakutat, AK: Yakutat Airport',
 401: 'Yuma, AZ: Yuma MCAS/Yuma International'}

In [14]:
df_1['carrier'] = encoder.fit_transform(df_1['carrier'])
carrier = {index : label for index, label in enumerate(encoder.classes_)}
carrier

C:\Users\sasan\AppData\Local\Temp\ipykernel_13044\1611633106.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['carrier'] = encoder.fit_transform(df_1['carrier'])

{0: '9E',
 1: 'AA',
 2: 'AS',
 3: 'B6',
 4: 'DL',
 5: 'EV',
 6: 'F9',
 7: 'G4',
 8: 'HA',
 9: 'MQ',
 10: 'NK',
 11: 'OH',
 12: 'OO',
 13: 'QX',
 14: 'UA',
 15: 'WN',
 16: 'YV',
 17: 'YX'}

In [15]:
x = df_1.drop('late_aircraft_delay', axis=1)
y = df_1['late_aircraft_delay']

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=20,random_state=44)
print("x_train shape is:",x_train.shape)
print("x_test shape is:",x_test.shape)
print("y_train shape is:",y_train.shape)
print("y_test shape is:",y_test.shape)

x_train shape is: (77423, 20)
x_test shape is: (20, 20)
y_train shape is: (77423,)
y_test shape is: (20,)

In [17]:
from sklearn.ensemble import RandomForestRegressor

In [18]:
RandomForestRegressorModel = RandomForestRegressor(n_estimators=100,max_depth=5, random_state=33)
RandomForestRegressorModel.fit(x_train, y_train)

print('Random Forest Regressor Train Score is : ' , RandomForestRegressorModel.score(x_train, y_train))
print('Random Forest Regressor Test Score is : ' , RandomForestRegressorModel.score(x_test, y_test))
print('----------------------------------------------------')

y_pred = RandomForestRegressorModel.predict(x_test)
print('Predicted Value for Random Forest Regressor is : ' , y_pred[:10])

Random Forest Regressor Train Score is :  0.9788934862254565
Random Forest Regressor Test Score is :  0.9769720616254477
----------------------------------------------------
Predicted Value for Random Forest Regressor is :  [ 256.31616372  431.09050955  103.46658217  103.46658217 2237.7437365
  103.46658217  968.85766683  256.31616372  256.31616372   42.46053312]

In [24]:
metrics.r2_score(y_test,y_pred)
print('MAE:', metrics.mean_absolute_error(y_test,y_pred))
print('MSE:', metrics.mean_squared_error(y_test,y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

MAE: 340.1524706540187
MSE: 466356.1030199806
RMSE: 682.9027039190727

In [25]:
metrics.r2_score(y_test,y_pred)

0.9769720616254477

In [21]:
from sklearn.ensemble import GradientBoostingRegressor
gbr=GradientBoostingRegressor(random_state=0)
GBR=gbr.fit(x_train,y_train)
pre=GBR.predict(x_test)

In [22]:
from sklearn import metrics
import numpy as np
print('MAE:', metrics.mean_absolute_error(y_test,pre))
print('MSE:', metrics.mean_squared_error(y_test,pre))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test,pre)))

MAE: 322.1680122181267
MSE: 475053.8663888325
RMSE: 689.241515282439

In [30]:
metrics.r2_score(y_test,pre)

0.9765425796104009

In [27]:
gg=pd.DataFrame({'Actual':y_test,'Predicted':pre})
gg

        Actual     Predicted
24096     91.0    186.565780
60262    261.0    294.219112
64050     62.0    124.217980
3038     104.0    124.217980
76168   1755.0   2486.008296
48598    100.0    124.217980
52458    702.0    811.710017
29993    110.0    215.069817
26457    467.0    307.833864
50372     18.0     96.568098
69710      0.0     38.636840
68783    153.0    124.217980
76621     68.0    124.217980
17353    873.0   1486.113485
22131  20465.0  17733.348892
13734   5955.0   5077.861255
25008    665.0   1190.078505
41909    231.0    191.375558
34484    360.0    286.407355
60792    776.0    735.436720

In [40]:
def predict_flight_delay(x):
    y= RandomForestRegressorModel.predict(x)
    if y<=15:
        print("flight is not delayed")
    else:
        print("flight is delayed and is in",2*int(y),"mins")

In [41]:
x_train

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay
71192,2020,4,4,3,334,326,1992.0,163.0,93.73,0.00,60.35,0.00,8.92,395.0,0.0,13404.0,10563.0,0.0,1773.0,0.0
26492,2022,8,12,14,188,174,31.0,6.0,4.00,1.00,0.00,0.00,1.00,0.0,0.0,562.0,104.0,301.0,0.0,0.0
44900,2021,9,9,5,85,85,113.0,11.0,4.79,1.00,1.55,0.48,3.17,1.0,0.0,468.0,116.0,40.0,42.0,47.0
31082,2022,5,7,1,146,134,17.0,2.0,0.11,0.00,1.62,0.00,0.27,0.0,0.0,187.0,6.0,0.0,166.0,0.0
67659,2020,7,14,17,333,332,57.0,6.0,4.38,0.00,1.62,0.00,0.00,0.0,0.0,437.0,343.0,0.0,94.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53177,2021,4,6,7,358,372,109.0,28.0,6.60,1.06,11.54,0.00,8.80,3.0,1.0,2158.0,360.0,152.0,560.0,0.0
49776,2021,6,6,7,30,150,52.0,7.0,1.29,0.00,2.81,0.00,2.90,0.0,0.0,447.0,97.0,0.0,64.0,0.0
25796,2022,8,4,3,254,180,88.0,12.0,8.89,0.00,2.05,0.00,1.06,2.0,0.0,833.0,691.0,0.0,118.0,0.0
69143,2020,6,16,11,171,384,539.0,45.0,14.00,4.00,27.00,0.00,0.00,0.0,0.0,2610.0,1219.0,163.0,1228.0,0.0
14114,2023,3,1,2,95,383,2464.0,639.0,164.35,9.09,167.26,0.91,297.38,23.0,3.0,48953.0,16434.0,764.0,5632.0,77.0

In [42]:
y_train

71192     1068.0
26492      157.0
44900      223.0
31082       15.0
67659        0.0
          ...
53177     1086.0
49776      286.0
25796       24.0
69143        0.0
14114    26046.0
Name: late_aircraft_delay, Length: 77423, dtype: float64

In [43]:
predict_flight_delay([[2020,4,4,3,334,326,1992.0,163.0,93.73,0.00,60.35,0.00,8.92,395.0,0.0,13404.0,10563.0,0.0,1773.0,0.0]])

flight is delayed and is in 1102 mins

C:\Users\sasan\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [32]:
predict_flight_delay([[2023,12,0,4,0,10,72,5,2.46,1,0.73,0,0.81,0,0,672,61,574,20,0]])

flight is delayed and is in [42.46053312]

C:\Users\sasan\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(